server:
  port: 8761
      
---
  
spring:
  config:
    activate:
      on-profile: dev
  
eureka: 
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
      
---
  
spring:
  config:
    activate:
      on-profile: test

eureka: 
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
      
---

spring:
  config:
    activate:
      on-profile: prod

eureka: 
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false