server:
  port: 8761
      
---
  
spring:
  profiles: dev
  
eureka: 
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
      
---
  
spring:
  profiles: test

eureka: 
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
      
---

spring:
  profiles: prod

eureka: 
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false